# Generated by Django 6.0.5 on 2026-06-14 07:52

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[2000, 1500], upload_to='products/main/', verbose_name='تصویر اصلی'),
        ),
    ]
