# Generated by Django 6.0.5 on 2026-06-14 07:54

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[1000, 800], upload_to='products/main/', verbose_name='تصویر '),
        ),
    ]
