# Generated by Django 6.0.5 on 2026-06-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_level_category_lft_category_rght_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
