"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gavi_!t%zl%o70p7y27&t8#!%^+tgfz#j%&&bx^^yux0r2a$z+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # package
    'rest_framework',
    'django_resized',
    'ckeditor',
    'ckeditor_uploader',
    'corsheaders',
    'mptt',

    # apps
    'accounts.apps.AccountsConfig',
    'cart.apps.CartConfig',
    'products.apps.ProductsConfig',
    'orders.apps.OrdersConfig',
    'contactUs.apps.ContactusConfig',
    'siteAssets.apps.siteAssetsConfig',

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "beautyShop",
        "USER": "louk",
        "PASSWORD": "louk2005",
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ckeditor
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'extraPlugins': ','.join([
            'uploadimage',  # فعال کردن پلاگین آپلود تصویر
        ]),
    },
}

# user
AUTH_USER_MODEL = 'accounts.User'

# jazzmin
JAZZMIN_SETTINGS = {
    # راست‌چین کردن منوها
    "site_title": "سایت من",
    "site_footer": "تمام حقوق محفوظ است © 2026",
    "menu_style": "default",
    "language": "fa",  # این قسمت رو به فارسی تغییر می‌دیم
    "custom_css": "css/custom.css",  # اگر بخوای استایل سفارشی اضافه کنی
    "custom_js": "js/custom.js",  # اگر جاوااسکریپت سفارشی داری
    "sidebar_nav": "horizontal",  # برای راست‌چین کردن نوار کناری می‌تونی این رو تغییر بدی
    "topmenu": True,  # منوی بالا رو فعال کن
    "user_avatar": None,  # اگر آواتار می‌خوای فعال باشه
    "site_logo": None,  # اگر لوگوی سفارشی داری

    # تنظیمات RTL (راست چین)
    "layout": {
        "body_class": "rtl",  # کلاس راست چین رو روی body تنظیم می‌کنیم
        "direction": "rtl",  # جهت صفحه رو راست چین کنیم
    },

    # سایر تنظیمات
    "icons": {
        "default": "fas fa-bars",  # آیکون منو
        "search": "fas fa-search",
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],

    "DEFAULT_THROTTLE_RATES": {
        "send_otp": "3/min",
    }

}

#kavenegar
KAVENEGAR_API_KEY = '4F48396C70454E7A4276445A732B506636624E547456665058596B4761716537506256574B47663253356B3D'
SMS_SENDER_NUMBER = '2000660110'


#zarinpal

ZARINPAL_MERCHANT_ID = "123e4567-e89b-12d3-a456-426614174000"

ZARINPAL_REQUEST_URL = (
    "https://sandbox.zarinpal.com/pg/v4/payment/request.json"
)

ZARINPAL_VERIFY_URL = (
    "https://sandbox.zarinpal.com/pg/v4/payment/verify.json"
)

ZARINPAL_STARTPAY_URL = (
    "https://sandbox.zarinpal.com/pg/StartPay/"
)

SITE_URL = "https://beaut.runflare.run/api/v1/"



# cors
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://beau.runflare.run",
    "https://beaut.runflare.run",
    "http://beau.runflare.run",
]
CSRF_TRUSTED_ORIGINS = [
    "https://beaut.runflare.run",
    "http://beau.runflare.run",
    "https://beau.runflare.run",

]
CORS_ALLOW_ALL_ORIGINS = False  # 👈 خیلی مهم


#jwt
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,

    "AUTH_HEADER_TYPES": ("Bearer",),
}




