# Generated by Django 6.0.5 on 2026-06-09 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits.', regex='^\\d{11}$')], verbose_name='شماره تماس')),
                ('message', models.TextField(blank=True, verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما',
                'ordering': ['phone'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('image', models.ImageField(blank=True, null=True, upload_to='location/images', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'موقعیت مکانی',
                'verbose_name_plural': 'موقعیت مکانی',
                'ordering': ['name'],
            },
        ),
    ]
